# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiAUg9_1L4OwO7Jx9pRva02zqIKay1_L
"""

def mahsulot(belgi):
  if belgi == "olma":
     return "15000"
  elif belgi == "coca cola":
    return "13000"
  elif belgi == "fanta":
    return "15000"
  elif belgi == "banan":
    return "25000"
  elif belgi == "uzum":
    return "10000"
  elif belgi == "daftar":
    return "3000"
  elif belgi == "ruchka":
    return "1000"
  elif belgi == "qalam":
    return "1500"
  elif belgi == "gazli suv":
    return "5000"
  elif belgi == "non":
    return "5000"
  elif belgi == "kitob":
    return "45000"
  elif belgi == "muzqaymoq":
    return "5000"
  elif belgi == "pepsi":
    return "15000"
  else:
    return "Mahsulot mavjud emas"
belgi = input("Mahsulotni kiriting=")
natija = mahsulot(belgi)
print(natija)